### ISSUE TITLE
Wizdler may not be fetching required dependencies?

### ISSUE THREAD

**Issue by EVILoptimist** [pepri/wizdler#16]
I am getting the same error referenced in #14 .

The WSDL I'm looking at is https://gateway.monster.com:8443/bgwBroker

After doing a little bit of digging, I found that the types that are "not found" are actually referenced, but they are included through a secondary file.

So If I am looking to use the `ExecuteQuery` method described in this WSDL, it says `No global element for root was found: Query (http://schemas.monster.com/Monster)`

This definition is actually included via the chain `https://gateway.monster.com:8443/bgwBroker` -> `http://schemas.monster.com/current/xsd/Monster.xsd` ->  `http://schemas.monster.com/current/xsd/Query.xsd`

I don't claim to be any type of an expert in the SOAP protocol or WSDL definitions. But, I hope that this is enough info for you to work with, and possibly shed some light on what might be happening in #14 as well.

Let me know if there's anything else you need from me! :)

**Comment by pepri** [comment]
Thank you for reporting the issue.

There are multiple ways to include content into WSDL: `wsdl:import`, `xs:import` and `xs:include`. Wizdler currently supports only `xs:import`. In this case, `Monster.xsd` is loaded via `xs:import`, but `Query.xsd` is not loaded, because it uses `xs:include`.

I will fix this issue in the next release, but there is no schedule for the release yet.

**Comment by EVILoptimist** [comment]
Perfect. Sounds good.

**Comment by pepri** [comment]
Fixed in 1.28.
